version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - 1883:1883
    expose:
      - "1883"
  web:
    restart: always
    build: ./web
    links:
      - mosquitto
    depends_on:
      - mosquitto
    expose:
      - "8000"
    ports:
      - 8000:80