version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - 1883:1883
    expose:
      - "1883"
  # postgres:
  #   restart: always
  #   build: ./postgres
  #   ports:
  #     - 5432:5432
  #   expose:
  #     - "5432"
  # redis:
  #   restart: always
  #   image: redis:latest
  #   ports:
  #     - 6374:6379
  #   expose:
  #     - "6374"
  web:
    restart: always
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./db.sqlite3:/home/ubuntu:src/db.sqlite3
    depends_on:
      - mosquitto