version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - 1883:1883
    expose:
      - "1883"
  postgres:
    restart: always
    build: ./postgres
    ports:
      - "5432"
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
  web:
    restart: always
    build: .
    links:
      - mosquitto
      - postgres
      - redis
    ports:
      - 9000:80
    depends_on:
      - postgres
