version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - 1883:1883
    expose:
      - "1883"
  postgres:
    restart: always
    build: ./postgres
    ports:
      - 5432:5432
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - "6379"
  web:
    restart: always
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
      - mosquitto