# Generated by Django 2.1.3 on 2018-11-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=150, verbose_name='장비 ID')),
                ('user_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='사용자 ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화 여부')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Mqtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(verbose_name='메세지')),
                ('topic', models.CharField(default='', max_length=180, verbose_name='토픽')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='시간')),
            ],
            options={
                'verbose_name': 'MQTT',
                'verbose_name_plural': 'MQTT',
                'db_table': 'mqtt',
            },
        ),
    ]
