# Generated by Django 2.1.1 on 2018-09-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mqtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(verbose_name='메세지')),
                ('topic', models.CharField(default='', max_length=180, verbose_name='토픽')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='시간')),
            ],
            options={
                'verbose_name': 'MQTT',
                'verbose_name_plural': 'MQTT',
                'db_table': 'mqtt',
            },
        ),
    ]
