# Generated by Django 2.1.3 on 2018-11-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
